#!/bin/sh -e

export DESTDIR="$1"

mkdir build
cd build

meson --prefix=/usr       \
      --buildtype=release \
      -Dvapi=enabled      \
      -Dgssapi=disabled   \
      -Dsysprof=disabled  \
      ..

ninja
ninja install
