#!/bin/sh -e

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Ddefault_library=both \
    -Denable-docs=false \
    -Denable-wayland=true \
    -Denable-x11=false \
    -Denable-xkbregistry=true \
    . output

ninja -C output
ninja -C output install
rsync -aqzL "include"/xkbcommon/* "$1/usr/include/xkbcommon/"
sync
