#!/bin/sh -e

mkdir -p bin
ln -sf /usr/bin/pigz  "$PWD/bin/gunzip"
ln -sf /usr/bin/gmake "$PWD/bin/make"
export PATH="$PWD/bin:$PATH"

./autogen.sh
./configure \
    --prefix=/usr

make
make DESTDIR="$1" install
