#!/usr/bin/env sh

patch -p1 < no-perl.patch
mkdir -p "$1/boot"
mkdir -p "$1/efi/EFI/kiss"

cp config .config
make olddefconfig

make

make \
    modules_install \
    INSTALL_MOD_PATH="$1/usr"

make \
    install \
    INSTALL_PATH="$1/boot"

# Set up the kernel
mv "$1/boot/vmlinuz"    "$1/boot/vmlinuz-$2"
mv "$1/boot/System.map" "$1/boot/System.map-$2"

# cp the efi executable to the EFI partition w/o the version
cp "$1/boot/vmlinuz-$2" "$1/efi/EFI/kiss/vmlinuz"
