#!/usr/bin/env sh


export CC=clang
export HOSTCC=clang
export CXX=clang++
export HOSTCXX=clang++
export CFLAGS="$CFLAGS -Wno-unused-but-set-variable"
export CXXFLAGS="$CXXFLAGS -std=c++20 -Wno-unused-but-set-variable"

sed -i 's/unsigned int  size0, size1, supp_size;/unsigned int  size0, size1;/g' src/hb-subset-cff1.cc
sed -i '/supp_size = 0;/d' src/hb-subset-cff1.cc
sed -i '/supp_size += SuppEncoding::static_size \* supp_codes.length;/d' src/hb-subset-cff1.cc
# Will store the built package's files to
# allow us to cherry-pick the ICU related files.
mkdir -p tmp
export DESTDIR="$PWD/tmp"

meson \
    --prefix=/usr \
    -Dglib=enabled \
    -Dicu=enabled \
    -Dicu_builtin=false \
    -Dbenchmark=disabled \
    -Dcairo=disabled \
    -Ddocs=disabled \
    . output

ninja -C output
ninja -C output install

install -Dt "$1/usr/lib"              tmp/usr/lib/libharfbuzz-icu*
install -Dt "$1/usr/lib/pkgconfig"    tmp/usr/lib/pkgconfig/harfbuzz-icu.pc
install -Dt "$1/usr/include/harfbuzz" tmp/usr/include/harfbuzz/hb-icu.h
