#!/bin/sh

install -Dm644 "boot/efi/EFI/efistub/vmlinuz.efi" "${KISS_ROOT}/boot/efi/EFI/efistub/vmlinuz.efi"
rsync -aqzL --exclude="efi" "boot/." "${KISS_ROOT}/boot/"
sync
grub-mkconfig -o "${KISS_ROOT}/boot/grub/grub.cfg"
