#! /bin/sh -e

interrupt_type="$(type "interrupt" > /dev/null && type "interrupt")" || :
[ ! -z "${interrupt_type:+x}" ] || {
  . /usr/include/kiss/share
  # [ -t 0 ] || // die 'fd 0' "does not work"
}

// log '$0' "$0"


version() {
	_level_2
	# local target="$1"
	# local target="$(// delegate -- target)"
	# // debug '$target' "$target"
	local _local_dir="$1"

	# local  repo_ver= repo_rel=

	version_target_major="$(grep "set(NVIM_VERSION_MAJOR" "$_local_dir/CMakeLists.txt" |
		awk "{print \$2}" | tr -d ')')"
	# export version_target_major
	version_target_minor="$(grep "set(NVIM_VERSION_MINOR" "$_local_dir/CMakeLists.txt" |
		awk "{print \$2}" | tr -d ')')"
	# export version_target_minor
	version_target_patch="$(grep "set(NVIM_VERSION_PATCH" "$_local_dir/CMakeLists.txt" |
		awk "{print \$2}" | tr -d ')')"
	# export version_target_patch
	# git
	version_target_suffix="$(grep "set(NVIM_VERSION_PRERELEASE" "$_local_dir/CMakeLists.txt" |
		awk "{print \$2}" | tr -d ')' | tr -d "\"")"
	# export version_target_suffix

	repo_ver="$version_target_major.$version_target_minor.$version_target_patch"
	repo_rel=0

	printf "$RS%s$FS%s" "$repo_ver" "$repo_rel"
}


target() {
	_level_2

	local upstream_name="$1"
	local _local_dir="$2"
	local url="$3"

	// log '$@' "$(esceval "$@")"

	[ -n "${UNUSE_LATEST_TAG:+x}" ] || upstream_name=

	local tag_list=
	local query_pid=
	local latest_target=
	local repo_ver= repo_rel=
	local repo_name="neovim"


	[ ! -z "${KISS_FORCE+x}" ] || {
		# refs/tags/vx.x.x-x
		tag_list="$( \
			git -C "$_local_dir" -c 'versionsort.suffix=-' ls-remote --exit-code --refs \
			--sort='version:refname' --tags "$url" 2> /dev/null |
			awk '{print $2}')" # & query_pid="$!"

		// log '$tag_list' "$(esceval "$tag_list")"
		# progress "$repo_name" "$query_pid" "git query"

		[ ! -z "$tag_list" ] || {
			# awk 'BEGIN{ FS = "/" } {print $NF}' 2> /dev/null || {
			git -C "$_local_dir" config --local --unset remote.origin.tagopt > /dev/null 2>&1
			git -C "$_local_dir" config --local --unset remote.origin.fetch > /dev/null 2>&1
			git -C "$_local_dir" config --local remote.origin.fetch \
			"+refs/heads/*:refs/remotes/origin/*" > /dev/null 2>&1
			tag_list="$( \
				git -C "$_local_dir" -c 'versionsort.suffix=-' ls-remote --exit-code --refs \
					--sort='version:refname' --tags "$url" 2> /dev/null |
					awk '{print $2}'
			)" # & query_pid="$!"
			# progress "$repo_name" "$query_pid" "git query"
		}

		[ -z "${upstream_name:+x}" ] ||
			tag_list="$(printf '%s\n' "$tag_list" | grep "$upstream_name")"

		[ -z "${tag_list:+x}" ] || {
			# printf "$RS%s$FS%s$FS%s" "" "$repo_ver" "$repo_rel"
			# return 0

			local latest_target_ref=
			latest_target_ref="$( \
				printf '%s' "$tag_list" | tail -n 1
				# tail -n 1 |
				# awk -F "/" '{print $NF}'
			)"

			latest_target="$(printf '%s' "$latest_target_ref" | awk 'BEGIN{ FS = "/" } {print $NF}' 2> /dev/null)"
		}
	}

	! // || / `version "$_local_dir" |
		awk -v rs="$RS" -v fs="$FS" 'BEGIN { FS = fs; RS = rs } \
	END { print "repo_ver=\""$1"\"; repo_rel=\""$2"\"" }' ||
	printf '%s\n' "return 1"`

	latest_target="nightly"

	// log '$latest_target' "$latest_target"
	// log '$repo_ver' "$repo_ver"
	// log '$repo_rel' "$repo_rel"

	printf "$RS%s$FS%s$FS%s" "$latest_target" "$repo_ver" "$repo_rel"

}

main() {
	_level_2
	local action="$1"
	shift 1
	// log '$action' "$action"
	// log '$@' "$(esceval "$@")"
	// "$action" "$@"
}

// main "$@"



