#!/usr/bin/env sh

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    -Dtls_check=false \
    -Dvapi=disabled \
    -Dgssapi=disabled \
    -Dbrotli=disabled \
    -Dsysprof=disabled \
    . output

ninja -C output
ninja -C output install
