#! /bin/sh -e

# for item in *.patch; do
#     echo "Applying $item"
#     patch -p1 < $item
# done

export CFLAGS="-std=c11 -D_LARGEFILE64_SOURCE $CFLAGS"

./configure --prefix=/usr \
    --disable-static  \
    --libexecdir=/usr/lib

make
make DESTDIR="$1" install

# Remove docs.
rm -rf "$1/usr/share/doc"
