#!/bin/sh -e

mkdir -p bin
ln -s /usr/bin/gmake "$PWD/bin/make"
export PATH="$PWD/bin:$PATH"

patch -p1 < colors.patch
patch -p1 < wld.patch
patch -p1 < drop_iso_14755.patch
patch -p1 < keybinds.patch

export LDFLAGS=" \
$LDFLAGS \
--static \
-L/usr/lib \
/usr/lib/libfontconfig.a \
-lfreetype \
/usr/lib/libxml2.a \
/usr/lib/libwld.a \
/usr/lib/libpixman-1.a \
-lswc \
-lexpat \
-ldrm \
-llzma \
-lpng \
"

make
make PREFIX=/usr install
