# Usage:
# env_prepend(PATH "$ENV{DESTDIR}/usr/bin")
macro(env_prepend env_name value)

  string(REPLACE ":" ";" PATH_LIST "$ENV{${env_name}}")
  set(index 0)
  foreach(path ${PATH_LIST})
    # message(STATUS "\${path} = ${path}")
    # if(path STREQUAL ".")
    #   message(WARNING "\${path} = ${path}")
    # endif()
    math(EXPR index "(${index} + 1)")
    message(STATUS "path [ ${index} ] = ${path}")
    if(index STREQUAL "1" AND NOT path STREQUAL "${value}")
      list(PREPEND PATH_LIST "${value}")
    endif()
  endforeach()
  # if(NOT "test" IN_LIST PATH_LIST)
  #   list(PREPEND PATH_LIST "test")
  #   list(APPEND  PATH_LIST "test")
  # endif()
  message(WARNING "\${PATH_LIST} = ${PATH_LIST}")
  # string(REPLACE ";" ":" ENV{${env_name}} "${PATH_LIST}")
  string(REPLACE ";" ":" PATH_LIST "${PATH_LIST}")
  # message(WARNING "\${PATH_LIST} = ${PATH_LIST}")
  set(ENV{${env_name}} ${PATH_LIST})
  message(WARNING "\$ENV{${env_name}} = $ENV{${env_name}}")

  # string(REPLACE ":" ";" PATH_LIST "$ENV{${env_name}}")
  # set(index 0)
  # foreach(path ${PATH_LIST})
  #   math(EXPR index "(${index} + 1)")
  #   message(STATUS "path [ ${index} ] = ${path}")
  # endforeach()

endmacro()

