#!/bin/sh -e

mkdir -p bin
ln -sf /usr/bin/pigz  "$PWD/bin/gunzip"
ln -sf /usr/bin/gmake "$PWD/bin/make"
export PATH="$PWD/bin:$PATH"

make \
	PREFIX=/usr \
	ENABLE_DEBUG=0 \
	LDFLAGS="$LDFLAGS --static" \
  PKG_CONFIG="pkg-config --static"

make PREFIX=/usr \
	ENABLE_DEBUG=0 \
	install

mkdir -p "$1/etc"
cp -f velox.conf.sample "$1/etc/velox.conf"
