#!/bin/sh -e

mkdir -p bin
ln -sf /usr/bin/gmake "$PWD/bin/make"
export PATH="$PWD/bin:$PATH"

(

echo "termkey stage"
mkdir -p bin
ln -sf /usr/bin/pigz  "$PWD/bin/gunzip"
ln -sf /usr/bin/gmake "$PWD/bin/make"
export PATH="$PWD/bin:$PATH"

cd termkey

make termkey.h libtermkey.la

mkdir -p "../usr/lib" \
    "../usr/include"

mv termkey.h "../usr/include"
mv .libs/*.a "../usr/lib"

)

(

echo "lpeg stage"
mkdir -p bin
ln -sf /usr/bin/pigz  "$PWD/bin/gunzip"
ln -sf /usr/bin/gmake "$PWD/bin/make"
export PATH="$PWD/bin:$PATH"

    # Lpeg doesn't have an option to create static libraries.
    cd lpeg
    for obj in lpcap lpcode lpprint lptree lpvm; do
        "${CC:-cc}" $CFLAGS -c -o $obj.o $obj.c
    done
    ar rcs ../usr/lib/liblpeg.a ./*.o
)

# http://www.leonerd.org.uk/code/libtickit/
# libtermkey is out of date
# http://www.leonerd.org.uk/code/libtermkey/
# (
# echo "libtermkey stage"
# mkdir -p bin
# ln -sf /usr/bin/pigz  "$PWD/bin/gunzip"
# ln -sf /usr/bin/gmake "$PWD/bin/make"
# export PATH="$PWD/bin:$PATH"
# cd termkey
# patch -p1 < ../static-no-libtool.patch
# # make
# make libtermkey.a
# # make libtermkey.so
# static_lib=$(find . -type f -name "libtermkey.a")
# [ -n "$static_lib" ] && cp $static_lib ../usr/lib/libtermkey.a
# lib=$(find . -type f -name "libtermkey.so")
# [ -n "$lib" ] && cp $lib ../usr/lib/libtermkey.so
# )

(

echo "vis stage"
mkdir -p bin
ln -sf /usr/bin/pigz  "$PWD/bin/gunzip"
ln -sf /usr/bin/gmake "$PWD/bin/make"
export PATH="$PWD/bin:$PATH"

cd vis

export CFLAGS="$CFLAGS -static -I../usr/include"
export LDFLAGS="$LDFLAGS -static -L../usr/lib"

./configure \
    --prefix=/usr \
    --enable-lua \
    --enable-liblpeg-static

make
make DESTDIR="$1" install
)
