#!/bin/sh
printf "\n* polybar-doc package includes a sample config file as /usr/share/doc/polybar/examples/config.ini
* In order to use it as a template, copy it as ~/.config/polybar/config.ini
* You may want to install some glyph fonts like font-siji in order to get symbols rendered correctly.\n"
