#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static"

for p in *.patch; do
    patch -p1 < "$p"
done

./configure \
    --prefix=/usr \
    --program-prefix=g

make
make DESTDIR="$1" install

ln -s gpatch "$1/usr/bin/patch"
ln -s gpatch.1 "$1/usr/share/man/man1/patch.1"
