#!/usr/bin/env sh

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Dbuildtype=release \
    -Ddbghelp=disabled \
    -Dintrospection=disabled \
    -Dexamples=disabled \
    -Ddoc=disabled \
    . output

ninja -C output
ninja -C output install
