#! /bin/sh -e
# Maintainer: Natanael Copa <ncopa@alpinelinux.org>
# Contributor: Leonardo Arena <rnalrd@alpinelinux.org>
# Contributor: Valery Kartel <valery.kartel@gmail.com>
#
# For debug information
SCRIPT_NAME="build" && export SCRIPT_NAME

pkg_name=${PWD##*/}
// log '$pkg_name' "$pkg_name"

: ${OBJ_ROOT:="$KISS_TMPDIR/objects"} && export OBJ_ROOT

OUTPUT_DIR="$OBJ_ROOT/$pkg_name" && export OUTPUT_DIR
# echo "\$OUTPUT_DIR = $OUTPUT_DIR"
// log '$OUTPUT_DIR' "$OUTPUT_DIR"

// log '$PWD' "$PWD"
[ "${MAKE_DIR-}" = "$PWD" ] ||
# : "${MAKE_DIR:="$PWD"}" && export MAKE_DIR
MAKE_DIR="$PWD" && export MAKE_DIR
// log '$MAKE_DIR' "$MAKE_DIR"

pkgdir="$1"
DESTDIR="$1"

pkgname=perl
pkgver=5.38.1
pkgrel=0
pkgdesc="Larry Wall's Practical Extraction and Report Language"
url="https://www.perl.org/"
arch="all"
license="Artistic-1.0-Perl OR GPL-1.0-or-later"
depends_dev="perl-utils=$pkgver-r$pkgrel"
makedepends="bzip2-dev zlib-dev"
subpackages="$pkgname-doc $pkgname-dev $pkgname-utils::noarch miniperl"
source="https://www.cpan.org/src/5.0/perl-$pkgver.tar.xz
	digest-sha-cflags.patch
	musl-skip-dst-test.patch
	skip-test-due-to-busybox-ps.patch
	musl-stack-size.patch
	release_status.patch
	"
# creates empty usr/local/{lib,share} for local sitedirs
options="!fhs"

# in perl core, removed from main/perl-scalar-list-utils
provides="
	perl-scalar-list-utils=$pkgver-r$pkgrel
	"

# secfixes:
#   5.38.1-r0:
#     - CVE-2023-47038
#   5.34.0-r1:
#     - CVE-2021-36770
#   5.30.3-r0:
#     - CVE-2020-10543
#     - CVE-2020-10878
#     - CVE-2020-12723
#   5.26.3-r0:
#     - CVE-2018-18311
#     - CVE-2018-18312
#     - CVE-2018-18313
#     - CVE-2018-18314
#   5.26.2-r1:
#     - CVE-2018-12015
#   5.26.2-r0:
#     - CVE-2018-6797
#     - CVE-2018-6798
#     - CVE-2018-6913
#   5.26.1-r0:
#     - CVE-2017-12837
#     - CVE-2017-12883

MAKE_DIR="$PWD" && export MAKE_DIR
: ${OUTPUT_DIR="$OBJ_ROOT/${PWD##*/}"} && export OUTPUT_DIR
find $OUTPUT_DIR -mindepth 1 -delete

_privlib=/usr/share/perl5/core_perl
_archlib=/usr/lib/perl5/core_perl

prepare() {
	# Most sources are readonly but we patch some
	chmod +w "$PWD"/*.c
	default_prepare

	# Ensure that we never accidentally bundle zlib or bzip2
	rm -rf cpan/Compress-Raw-Zlib/zlib-src
	rm -rf cpan/Compress-Raw-Bzip2/bzip2-src
	sed -i '/\(bzip2\|zlib\)-src/d' MANIFEST
}
prepare

# default_prepare included patching
# for item in *.patch; do
# 	patch -p1 < "$item"
# done

cd "$OUTPUT_DIR"

build() {
	export BUILD_ZLIB=0
	export BUILD_BZIP2=0
	export BZIP2_LIB=/usr/lib
	export BZIP2_INCLUDE=/usr/include

	# language runtime
	# export CFLAGS="$CFLAGS -O2 -flto=auto"
	export CFLAGS="$CFLAGS -DNO_POSIX_2008_LOCALE -D_GNU_SOURCE -fno-lto -fPIC"
	export LDFLAGS="$LDFLAGS -pthread -fno-lto"

	crossopt=
	[ "$KISS_XBUILD_TRIPLE" = "$KISS_XHOST_TRIPLE" ] ||
    crossopt=-Dusecrosscompile

	# git clean -dxf
	# make realclean
	# make distclean


	config() {
		# sh $MAKE_DIR/configure \
		# ./configure \
		# sh $MAKE_DIR/Configure \

		$MAKE_DIR/Configure \
			-d \
			-Dusedevel \
			-Dsrc=$MAKE_DIR \
			-Des \
    		-Dusevendorprefix \
    		-Dusesoname \
    		-Dccflags="$CFLAGS" \
    		-Dccdlflags="$CFLAGS" \
    		-Dcccdlflags="$CFLAGS" \
    		-Dldflags="$CFLAGS $LDFLAGS" \
    		-Dlddlflags="-shared $CFLAGS $LDFLAGS" \
    		-Dshrpldflags="$CFLAGS" \
    		-Dlkflags="$CFLAGS" \
    		$crossopt \
    		-Dar="${AR:-ar}" \
    		-Dnm="${NM:-nm}" \
    		-Dranlib="${RANLIB:-ranlib}" \
    		-Dreadelf="${READELF:-readelf}" \
    		-Dobjdump="${OBJDUMP:-objdump}" \
			-Dprefix=/usr \
			-Dprivlib=$_privlib \
			-Darchlib=$_archlib \
			-Dlocincpth="" \
			-Doptimize="$CFLAGS" \
			-Duselargefiles \
			-Dusethreads \
			-Duseshrplib \
			-Dd_semctl_semun \
			-Dman1ext='1' \
			-Dman3ext='3pm' \
			-Dcf_by='kiss' \
			-Ud_csh \
			-Ud_fpos64_t \
			-Ud_off64_t \
			-Dusenm \
    		-Dinc_version_list=none \
    		-Dd_sockaddr_in6=define \
    		-Dperl_static_inline="static __inline__" \
			-Dmyhostname=kiss \
			-Dsiteprefix=/usr \
			-Dman1dir=/usr/share/man/man1 \
			-Dman3dir=/usr/share/man/man3 \
			-Dinstallman1dir=/usr/share/man/man1 \
			-Dinstallman3dir=/usr/share/man/man3 \
			-Dsitelib=/usr/share/perl5/site_perl \
			-Dsitearch=/usr/lib/perl5/site_perl \
			-Dvendorprefix=/usr \
			-Dvendorlib=/usr/share/perl5/vendor_perl \
			-Dvendorarch=/usr/lib/perl5/vendor_perl \
			-Dmksymlinks \
			-D_FORTIFY_SOURCE \
    		-Dd_static_inline

			# -Dsiteprefix=/usr \
			# -Dman1dir=/usr/share/man/man1 \
			# -Dman3dir=/usr/share/man/man3 \
			# -Dinstallman1dir=/usr/share/man/man1 \
			# -Dinstallman3dir=/usr/share/man/man3 \
			# -Dsitelib=/usr/share/perl5/site_perl \
			# -Dsitearch=/usr/lib/perl5/site_perl \
			# -Dvendorprefix=/usr \
			# -Dvendorlib=/usr/share/perl5/vendor_perl \
			# -Dvendorarch=/usr/lib/perl5/vendor_perl \

			# ./configure \
			# 	-Dsrc=$MAKE_DIR \
    		# 	--prefix=/usr \
    		# 	--build=$KISS_XBUILD_TRIPLE \
    		# 	--target=$KISS_XHOST_TRIPLE \
    		# 	--sysroot=${KISS_ROOT:-/} \
    		# 	-Des \
    		# 	-Dvendorprefix=/usr \
    		# 	-Dusevendorprefix \
    		# 	-Duseshrplib \
    		# 	-Dusesoname \
    		# 	-Dusethreads \
    		# 	-Dccflags="$CFLAGS" \
    		# 	-Dccdlflags="$CFLAGS" \
    		# 	-Dcccdlflags="$CFLAGS" \
    		# 	-Dlddlflags="-shared $CFLAGS $LDFLAGS" \
    		# 	-Dshrpldflags="$CFLAGS" \
    		# 	-Dldflags="$CFLAGS $LDFLAGS" \
    		# 	-Dlkflags="$CFLAGS" \
    		# 	-Doptimize="-Wall" \
    		# 	$crossopt \
    		# 	-Dar="${AR:-ar}" \
    		# 	-Dnm="${NM:-nm}" \
    		# 	-Dranlib="${RANLIB:-ranlib}" \
    		# 	-Dreadelf="${READELF:-readelf}" \
    		# 	-Dobjdump="${OBJDUMP:-objdump}" \
    		# 	-Dinc_version_list=none \
    		# 	-Dd_sockaddr_in6=define \
    		# 	-Dperl_static_inline="static __inline__" \
    		# 	-Dd_static_inline

			# -Dmksymlinks \
			# -Dtargethost=$KISS_XBUILD_TRIPLE \
    		# --build=$KISS_XBUILD_TRIPLE \
    		# --target=$KISS_XHOST_TRIPLE \
    		# --sysroot=${KISS_ROOT:-/} \
			# -Dcccdlflags='-fPIC' \
			# -Dccdlflags='-rdynamic' \

	}
	config

	make libperl.so && make
}
build
check() {
	// log 'check' "perl"
	export CI=true
	export LC_ALL=C

	# Perl tests HARNESS_OPTIONS against the regex
	# /^j(\d*)$/, if $JOBS is unset, it defaults to 9
	export HARNESS_OPTIONS=j"$JOBS"
	export PERL_TEST_HARNESS_ASAP=1

	make test_harness_notty
}
# check
package() {
	// log 'package' "perl"
	make DESTDIR="$pkgdir" install

	# Omit global flto afterward
	# perl saves compile-time cflags and applies them to every future build
	sed -i \
		-e "s| -flto=auto||g" \
		"$pkgdir"/usr/lib/perl5/core_perl/Config_heavy.pl

	if [ -n "$(find "$pkgdir"/usr/local -type f 2> /dev/null)" ]; then
		error "files found under /usr/local"
		return 1
	fi

	install -Dm755 miniperl \
		-t "$pkgdir"/usr/bin/

	# Delete files starting with a dot,
	# but really just usr/lib/perl5/core_perl/.packlist
	find "$pkgdir" -name '.*' -delete

	\ls -1 "$pkgdir"/*.0 | xargs \rm -f || :
}
package
miniperl() {
	// log 'miniperl' "perl"
	amove usr/bin/miniperl || :
}
miniperl
doc() {
	// log 'doc' "perl"
	local file; find "$pkgdir" -name "*.pod" | while read -r file; do
		amove "${file#"$pkgdir"}"
	done
	default_doc
}
# doc
dev() {
	// log 'dev' "perl"
	amove \
		$_archlib/Devel \
		$_privlib/Encode \
		usr/bin/h2xs \
		usr/bin/perlivp \
		usr/bin/enc2xs \
		usr/bin/xsubpp

	default_dev
}
dev
utils() {
	// log 'utils' "perl"
	pkgdesc="$pkgdesc (misc utilities)"
	depends="$pkgname=$pkgver-r$pkgrel"

	amove \
		usr/bin/corelist \
		usr/bin/cpan \
		usr/bin/encguess \
		usr/bin/libnetcfg \
		usr/bin/h2ph \
		usr/bin/instmodsh \
		usr/bin/json_pp \
		usr/bin/perlbug \
		usr/bin/perlthanks \
		usr/bin/piconv \
		usr/bin/pl2pm \
		usr/bin/prove \
		usr/bin/ptar \
		usr/bin/ptardiff \
		usr/bin/ptargrep \
		usr/bin/shasum \
		usr/bin/splain \
		usr/bin/zipdetails
}
utils
sha512sums="
720b2c2707f219509e652bc3d80f9ce82bec85f882dee9ff88b6bc5183064d66333651830daeb92a6e96bbe5d9d48581ab8496ce9427f8db6103fc438e2c05db  perl-5.38.1.tar.xz
59afa4c166e4808d355e19cd70748540ffce9da5c6919c71648be7678de328409f9121ddea33415add73fc01a22e95ed9d9629f31b8ba20b3bbfc04dab926c63  digest-sha-cflags.patch
3eaec691bc38e208ba4f34130ae45e50b6c339fa50093d0b0f6d7f24cb5b7c2a3734ca714a279c4b51173f82e46a8e7a3e70bfc7d7471a18c55a2102140e4186  musl-skip-dst-test.patch
ba9cb1ff4a6e8e4c31bf4ef132c071ac919ffe45842cf5e98c8ca72d78ef4803883b57a0e7b8037da0079561a6ce9e6bd8d127892ac1bcb047638cb3ba3157f6  skip-test-due-to-busybox-ps.patch
c004d6612ec754e5947255a2e2d15b5581f187c32495aeeec9f4fa286919bd9f40c72b63db61e3f4004b09288af2063a6a14b67e5c289e9a8b23ebd7c216e16f  musl-stack-size.patch
ec2c0680588772e64a2a3baf27a644f54b2723ca5a7038b646334a4b25fff2674fcd3ad57380bfe8513fe61bccd1583eff5ee366075d5b5e2880ce131f30e80b  release_status.patch
"
