#!/bin/sh -e

unset DESTDIR
mkdir -p bin
ln -s /usr/bin/pigz  "$PWD/bin/gunzip"
ln -s /usr/bin/gmake "$PWD/bin/make"
export PATH="$PWD/bin:$PATH"

make CC="${CC:-cc}" EFIDIR=/boot/EFI efibootmgr

mkdir -p \
    "$1/usr/bin" \
    "$1/usr/share/man/man8"

cp -f src/efibootmgr   "$1/usr/bin"
cp -f src/efibootmgr.8 "$1/usr/share/man/man8"
