#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --build=$CBUILD \
    --host=$CHOST \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --with-libidn \
    --with-ssl=openssl \
    --disable-nls

make
make DESTDIR="$1" install

