#!/usr/bin/env sh

mkdir -p bin
ln -s /usr/bin/pigz  "$PWD/bin/gunzip"
ln -s /usr/bin/gmake "$PWD/bin/make"
export PATH="$PWD/bin:$PATH"

make MYCFLAGS="$CFLAGS -fPIC" \
     MYLDFLAGS="$LDFLAGS" \
     posix

make INSTALL_TOP="$1/usr" \
     INSTALL_MAN="$1/usr/share/man/man1" \
     INSTALL_DATA="cp -d" \
     install

install -Dm 644 lua.pc "$1/usr/lib/pkgconfig/lua.pc"
