#!/bin/sh -e

sed -e '/libevdev/d' < sway/meson.build  > _
mv -f _ sway/meson.build
# search="wlroots_version = '\[''\''>=0.10.0'\'', '\''<0.11.0'\'''\]'"
search="wlroots_version = ['>=0.10.0', '<0.11.0']"
search=$(echo "${search}" | sed 's/[^^]/[&]/g; s/\^/\\^/g')
replace="wlroots_version = ['>=0.10.0']"
replace=$(echo "${replace}" | sed 's/[^^]/[&]/g; s/\^/\\^/g')
# sed -e '/libevdev/d' \
#     -e "s/${search}/${replace}/g" \
#     < meson.build  > _
# mv -f _ meson.build

sed -e '/libevdev/d' < meson.build  > _
mv -f _ meson.build

awk "{sub(/wlroots_version = \[\'>=0.10.0\', \'<0.11.0\'\]/,\
\"wlroots_version = \[\'>=0.10.0\'\]\")}1" < meson.build  > _
mv -f _ meson.build

replace_header() {
    sed -e 's/#include <libevdev\/libevdev.h>/#include <linux\/input.h>/g' \
        < "$1" > _
    mv -f _ "$1"
}

for item in \
        "sway/commands/bar/bind.c" \
        "sway/commands/input/scroll_button.c" \
        "sway/commands/bind.c" \
        "sway/ipc-json.c" \
        "sway/input/seatop_default.c" \
        "sway/input/cursor.c"; do
    replace_header "$item"
done

patch -p1 < no-evdev.patch
# patch -p1 < pcre2.patch

# Default background color.
sed 's/0.25f, 0.25f, 0.25f/0.929, 0.870, 0.678/' \
    sway/desktop/render.c > _
mv -f _ sway/desktop/render.c

sed 's:output \* bg \@datadir\@/backgrounds/sway:# output \* bg \@datadir\@/backgrounds/sway:' \
    ./config.in > _
mv -f _ ./config.in

# sed -i "s/libinput = dependency('libinput', /libinput = dependency('libinput', static: true, /g" meson.build

# # sed -i "s/void list_insert(list_t *list, int index, void *item);/inline void list_insert(list_t *list, int index, void *item);/g" include/list.h
# sed -i "s/void list_insert(list_t *list, int index, void *item);/inline void sway_list_insert(list_t *list, int index, void *item);/g" include/list.h
# sed -i "s/void list_insert(list_t *list, int index, void *item) {/void sway_list_insert(list_t *list, int index, void *item) {/g" common/list.c
#
#
# # sed -i "s/sway_inc = include_directories('include')/sway_inc = include_directories('$1/include')/g" meson.build
# # sed -i "s/include_directories: [sway_inc],/include_directories: sway_inc,/g" ./sway/meson.build
# sed -i 's/#include "list.h"/#include "../include/list.h"/g' ./sway/config.c
# sed -i "s/list_insert(/sway_list_insert(/g" ./sway/config.c
# sed -i "s/list_insert(/sway_list_insert(/g" ./sway/tree/workspace.c
# sed -i "s/list_insert(/sway_list_insert(/g" ./sway/tree/container.c
# export CFLAGS="$CFLAGS -static -I$1/include"
# export LDFLAGS="$LDFLAGS -static"

list_operation=$(find . -type f -name "list.h")
echo "list_operation: $list_operation"

# Build fails with gcc 12 due to -Werror.
export CFLAGS="$CFLAGS -UWLR_HAS_X11_BACKEND -Wno-error"
export PKG_CONFIG_SYSROOT_DIR=

kiss-meson-config > meson.config

meson \
    --prefix=/usr \
    --cross-file=meson.config \
    -Dseatd:builtin=enabled \
    -Dseatd:libseat-builtin=enabled \
    -Ddefault_library=static \
    -Dxwayland=disabled \
    -Ddefault-wallpaper=false \
    -Dzsh-completions=false \
    -Dbash-completions=false \
    -Dfish-completions=false \
    . build

    # -Dseatd:builtin=enabled \

ninja -C build

swaywm=$(find . -type f -name "sway")
for I in $swaywm; do
    printf "%-20s = %s\n" "swaywm" "$I"
done
list_folder=$(ls build/sway)
for I in $list_folder; do
    printf "%-20s = %s\n" "ls build/sway" "$I"
done
[ -d "$1/usr/bin" ] || mkdir -p "$1/usr/bin"
install -m755 "build/sway/sway" "$1/usr/bin/sway"
list_config_in=$(find . -type f -name "config.in")
for I in $list_config_in; do
    printf "%-20s = %s\n" "config.in" "$I"
done

[ -d "$1/etc/sway" ] || mkdir -p "$1/etc/sway"
cp -f config.in "$1/etc/sway/config"

ninja -C build install

[ -d "$1/usr/lib" ] || mkdir -p "$1/usr/lib"
[ ! -f "/usr/lib/libwlroots.so.11" ] ||
[ "$(readlink -f "$1/usr/lib/libwlroots.so.10")" == "/usr/lib/libwlroots.so.11" ] || {
    rm -f "$1/usr/lib/libwlroots.so.10"
    ln -sf "/usr/lib/libwlroots.so.11" "$1/usr/lib/libwlroots.so.10"
}
