#! /bin/sh -e

./configure \
	--prefix=/usr \
	--program-prefix=b \
	--enable-btyacc

make LDFLAGS="$LDFLAGS -static"
make DESTDIR="$1" install

# Symlink to yacc
ln -s byacc "$1/usr/bin/yacc"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/byacc.license"

