#! /bin/sh -e

version_target="$2"

[ ! -d "$KISS_ROOT/usr/lib/clang" ] || {
	cd "$KISS_ROOT/usr/lib/clang"

	[ ! -d "system" ] || mv "system" "system.backup"

	[ ! -d "$version_target" ] ||
	[ "$(readlink -f "system")" == "$version_target" ] ||
	ln -s -f "$version_target" "system"
}

[ ! -d "$KISS_ROOT/usr/lib/llvm" ] || {
	cd "$KISS_ROOT/usr/lib/llvm"

	[ ! -d "system" ] || mv "system" "system.backup"

	[ ! -d "$version_target" ] ||
	[ "$(readlink -f "system")" = "$version_target" ] ||
	ln -s -f "$version_target" "system"
}
