/* ISC license. */

/* Generated by: ./configure --enable-shared --enable-static --disable-allstatic --libdir=/usr/lib --libexecdir=/lib/utmps --with-lib=/usr/lib --with-dynlib=/lib */

#ifndef UTMPS_CONFIG_H
#define UTMPS_CONFIG_H

#define UTMPS_VERSION "0.1.2.1"
#define UTMPS_BINPREFIX ""
#define UTMPS_EXTBINPREFIX ""
#define UTMPS_LIBEXECPREFIX "/lib/utmps/"
#define UTMPS_UTMPD_PATH "/run/utmps/.utmpd-socket"
#define UTMPS_WTMPD_PATH "/run/utmps/.wtmpd-socket"

#endif
