#!/usr/bin/env sh

mkdir -p bin
ln -sf /usr/bin/pigz  "$PWD/bin/gunzip"
ln -sf /usr/bin/gmake "$PWD/bin/make"
export PATH="$PWD/bin:$PATH"

export DESTDIR="$1"


./configure \
    --prefix=/usr \
    --disable-gcov

make
make install
