#!/bin/sh -e

mkdir -p bin
ln -s /usr/bin/gmake "$PWD/bin/make"
export PATH="$PWD/bin:$PATH"

./configure \
    --prefix=/usr \
    --libexecdir=/usr/bin \
    --localstatedir=/var \
    --disable-dbus

make
make install

cp -f iwd_passphrase "$1/usr/bin"

# Install runit service.
mkdir -p "$1/etc/sv/eiwd"
cp -f  eiwd.run                  "$1/etc/sv/eiwd/run"
ln -sf /run/runit/supervise.eiwd "$1/etc/sv/eiwd/supervise"
