# This file was generated by:
# ./configure --enable-shared --enable-static --disable-allstatic --libdir=/usr/lib --libexecdir=/lib/utmps --with-lib=/usr/lib --with-dynlib=/lib
# Any changes made here will be lost if configure is re-run.

target := x86_64-unknown-linux-musl
package := utmps
prefix := 
exec_prefix := 
dynlibdir := /lib
libexecdir := /lib/utmps
bindir := /bin
libdir := /usr/lib
includedir := /usr/include
sysdeps := /usr/lib/skalibs/sysdeps
slashpackage := false
sproot := 
version := 0.1.2.1
home := 
exthome := 
SPAWN_LIB := 
SOCKET_LIB := 
SYSCLOCK_LIB := 
TIMER_LIB := 
UTIL_LIB := 

CC := cc
CPPFLAGS_AUTO := -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -iquote src/include-local -Isrc/include -fPIC -Werror=implicit-function-declaration -Werror=implicit-int -Werror=pointer-sign -Werror=pointer-arith
CPPFLAGS :=  --target=x86_64-linux-musl -O3 -pipe -fPIC -march=x86-64 -mtune=native
CFLAGS_AUTO := -pipe -Wall -std=c99 -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections
CFLAGS := -O2 -fomit-frame-pointer --target=x86_64-linux-musl -O3 -pipe -fPIC -march=x86-64 -mtune=native
LDFLAGS_AUTO := -Wl,--sort-section=alignment -Wl,--sort-common
LDFLAGS := -Wl,--hash-style=both -Wl,--as-needed,-O1,--sort-common
LDFLAGS_SHARED := -shared -L/lib
LDFLAGS_NOSHARED :=  -L/lib
CROSS_COMPILE := 

vpath lib%.a /usr/lib
vpath lib%.so /lib
.LIBPATTERNS := lib%.so
DO_STATIC := 1
DO_SHARED := 1
STATIC_LIBS_ARE_PIC := 1
DO_LIBC_INCLUDES :=
LIBNSSS :=
MAYBEPTHREAD_LIB :=
