#!/bin/sh -e

meson . objects \
    --prefix=/usr \
    --sysconfdir=/etc \
    -Dwayland-backend=true \
    -Dmacos-backend=false \
    -Dx11-backend=false \
    -Dwin32-backend=false \
    -Ddemos=false \
    -Ddebug=false \
    -Dbuild-examples=false \
    -Dbuild-tests=false

    # -Dquartz_backend=false \
    # -Dinstall-tests=false \
    # --reconfigure
    # -Dmedia-gstreamer=disabled \
    # -DXCB-shm=disabled \
    # -DXlib=disabled \
    # -DXlib-Xrender=disabled \
    # -Dxlib-xcb=disabled \


ninja -C objects

ninja -C objects install
