#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Dexamples=false \
    -Dsbindir=bin \
    -Dudevrulesdir=/usr/lib/udev \
    -Duseroot=false \
    . output

ninja -C output
ninja -C output install

# Add the setuid flag to the fusermount3 executable.
# NB: the useroot option does that too but it also adds device nodes which we
# don't need. That's why we have to do this manually.
chmod u+s "$DESTDIR/usr/bin/fusermount3"

# Remove the module loading init script.
# It's easier (and simpler) to just compile the module in the kernel.
rm -rf "$1/etc/init.d"
