#! /bin/sh -e

interrupt_type="$(type "interrupt" > /dev/null && type "interrupt")" || :
[ ! -z "${interrupt_type:+x}" ] || {
  . /usr/include/kiss/share
  # [ -t 0 ] || // die 'fd 0' "does not work"
}

version() {
	_level_2
	local _local_dir="$1"

	repo_ver="2.4.7"

	repo_rel=0

	printf "$RS%s$FS%s" "$repo_ver" "$repo_rel"
}

target() {
	_level_2
	local upstream_name="$1"
	local _local_dir="$2"
	local url="$3"
	local tag_list=
	local query_pid=
	local latest_target=
	local repo_ver= repo_rel=
	# // version "$_local_dir"
	! // || / `version "$_local_dir" |
		awk -v rs="$RS" -v fs="$FS" 'BEGIN { FS = fs; RS = rs } \
	END { print "repo_ver=\""$1"\"; repo_rel=\""$2"\"" }' ||
	printf '%s\n' "return 1"`

	latest_target="v$repo_ver"

	// log '$latest_target' "$latest_target"
	// log '$repo_ver' "$repo_ver"
	// log '$repo_rel' "$repo_rel"

	printf "$RS%s$FS%s$FS%s" "$latest_target" "$repo_ver" "$repo_rel"

}

main() {
	_level_2
	local action="$1"
	shift 1
	// log '$action' "$action"
	// log '$@' "$(esceval "$@")"
	// "$action" "$@"
}

// main "$@"
