#! /bin/sh -e

sed -i '/test.lock/s/^/#/' gnulib-tests/gnulib.mk

# autoreconf -fvi

export CFLAGS="$CFLAGS -static"

FORCE_UNSAFE_CONFIGURE=1 \
	./configure \
	--prefix=/usr \
	--enable-no-install-program=kill,uptime

make
make DESTDIR="$1" install
