#!/bin/sh -e

setcap cap_net_raw+p "$(readlink -f "$(command -v /usr/bin/ping)")"
setcap cap_net_raw+p "$(readlink -f "$(command -v /usr/bin/clockdiff)")"
setcap cap_net_raw+p "$(readlink -f "$(command -v /usr/bin/arping)")"
