#! /bin/sh -e

export CFLAGS="$CFLAGS -fPIC"

# patch -p1 < cross.patch

# ./configure \
#     --prefix=/usr \
#     --archs="-arch $KISS_XHOST_ARCH"

OUTPUT_DIR="$OBJ_ROOT/zlib-ng"

cmake -S . -B "${OUTPUT_DIR}" -DCMAKE_INSTALL_PREFIX=/usr
# cmake -S . -B "${OUTPUT_DIR}" -DCMAKE_INSTALL_PREFIX=/usr \
# -UZLIB_COMPAT

# make CC=clang CXX=clang++
cmake --build "${OUTPUT_DIR}" --target all --parallel

# make DESTDIR="$1" PREFIX=/usr CC=clang CXX=clang++ install
cmake  --build "${OUTPUT_DIR}" --target install --parallel

# Install the license
install -Dm755 LICENSE.md "$1/usr/share/LICENSES/zlib.license"
