#!/usr/bin/env sh

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    -D html_manual=false \
    -D pipe=false \
    . output

ninja -C output
ninja -C output install
