#!/usr/bin/env sh

export CFLAGS="$CFLAGS -isystem /usr/include/libr"
export CXXFLAGS="$CXXFLAGS -isystem /usr/include/libr"

# autoreconf -vif
./bootstrap

./configure \
    --prefix=/usr

make
make install
