#!/usr/bin/env sh

unset DESTDIR
mkdir -p bin
ln -s /usr/bin/pigz  "$PWD/bin/gunzip"
ln -s /usr/bin/gmake "$PWD/bin/make"
export PATH="$PWD/bin:$PATH"

# CCLD="clang"
export CFLAGS="$CFLAGS -Wno-unused-command-line-argument"

# Disable test program 'thread-test' as it causes build failures when using
# parallel make (due to missing dependency on libefivar.so). Other workarounds
# include patching the Makefile or forcing -j1 (what we used to do).
# See: https://github.com/rhboot/efivar/pull/169
sed 's/thread-test//' src/Makefile > _
mv -f _ src/Makefile

export HOSTCC="clang"
export HOST_CFLAGS=""
export HOST_LDFLAGS=""

CC=clang
CXX=clang++
LD=/usr/bin/ld.lld

# Avoid repeating ourselves.
mk() {
    make HOST_MARCH="" COMPILER="$CC" \
        libdir=/usr/lib/              \
        bindir=/usr/bin/              \
        mandir=/usr/share/man/        \
        includedir=/usr/include/      \
        "$@"
    }

export CC="${CC:-cc}"

mk
mk DESTDIR="$1" install
