#!/bin/sh -e

mkdir -p bin
ln -s /usr/bin/gmake "$PWD/bin/make"
export PATH="$PWD/bin:$PATH"

# https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix
./configure --prefix="/usr" \
    --with-lua-include=/usr/include/luajit-2.1

make
# make DESTDIR="$1" PREFIX=/usr bootstrap
make DESTDIR="$1" PREFIX=/usr install
