#!/usr/bin/env sh

export PKG_CONFIG_SYSROOT_DIR=
export CC=clang
export CXX=clang++
export HOST_CC=clang
export BUILD_CC=clang
export HOST_CXX=clang++
export BUILD_CXX=clang++
export TARGET=visurf
export PREFIX=/usr
export LIBDIR=lib
export INCLUDEDIR=include
export BUILD="$KISS_XBUILD_TRIPLE"
export HOST="$KISS_XHOST_TRIPLE"
export shell=${SHELL}

patch -p1 < nsgenbind.patch
patch -p1 < testament.patch

rm -Rf netsurf
rm -Rf libcss
mv visurf netsurf
mv libcss-new libcss
host_aquire=$(find . -type f -name "Makefile.tools" | grep "share")
echo "host_aquire = $host_aquire"
# host_aquire = ./inst-visurf/share/netsurf-buildsystem/makefiles/Makefile.tools

# Something up with how kiss does the git checkout
# Not dealing with symlink correctly?
touch netsurf/frontends/visurf/res/Messages

make
sed -i 's/shell//g' "$host_aquire"
make DESTDIR="$1" PREFIX="/usr" install
