#!/bin/sh -e

export PKG_CONFIG_SYSROOT_DIR=
export HOST_CC=clang
export HOST_CXX=clang++
# Makefile:116: *** Unknown TARGET "netsurf", Must be one of riscos gtk2 gtk3 beos amiga amigaos3 framebuffer windows atari monkey.  Stop.
export TARGET=gtk3
export PREFIX=/usr
export LIBDIR=lib
export INCLUDEDIR=include
export BUILD="$KISS_XBUILD_TRIPLE"
export HOST="$KISS_XHOST_TRIPLE"

make
make install
