#!/usr/bin/env sh

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --sbindir=/usr/bin \
    --bindir=/usr/bin \
    --enable-hwdb \
    --enable-blkid=auto \
    --disable-introspection

make
make DESTDIR="$1" install

# Install runit service.
mkdir -p "$1/etc/sv/udevd"
cp -f udevd.run "$1/etc/sv/udevd/run"
ln -sf /run/runit/supervise.udevd "$1/etc/sv/udevd/supervise"
