#!/bin/sh

file_list="aplay/aplay.c
axfer/container.h
axfer/container.c
axfer/container-voc.c
axfer/test/mapper-test.c
axfer/test/container-test.c"

for item in $file_list; do
    echo "Replace off64_t with off_t in $item"
    sed -e 's/off64_t/off_t/g' "$item" > _
    mv -f _ "$item"
done
sed -e 's/lseek64/lseek/g' "aplay/aplay.c" > _
mv -f _ "aplay/aplay.c"

./configure \
    --prefix=/usr \
    --build=$KISS_XBUILD_TRIPLE \
    --host=$KISS_XHOST_TRIPLE \
    --sbindir=/usr/bin \
    --with-udev-rules-dir=/usr/lib/udev/rules.d \
    --disable-alsaconf \
    --disable-bat \
    --disable-xmlto \
    --disable-nls

make
make install
