#! /bin/sh -e

[ -n "${KISS_XHOST_ABI+x}" ] ||
KISS_XHOST_ABI="$(ldd --version 2>&1 | grep musl | awk '{print $1}')"
[ "$KISS_XHOST_ABI" != "musl" ] ||
CXXFLAGS="-DLIBCXX_HAS_MUSL_LIBC=1 $CXXFLAGS"

CXXFLAGS="-isystem /usr/include/tirpc $CXXFLAGS"

[ ! -d "Modules" ] || mv Modules/* cmake/Modules/

# Don't set the compiler here, interferes with 2-stage build
kiss-cmake-config | sed '/CMAKE_C_COMPILER/d;' | sed '/CMAKE_CXX_COMPILER/d;' > cmake.config || kill 0

sed -i 's/set(CMAKE_CXX_STANDARD 17 CACHE STRING "C++ standard to conform to")/set(CMAKE_CXX_STANDARD 20 CACHE STRING "C++ standard to conform to")/g' \
    "CMakeLists.txt"

cmake -B objects -G Ninja \
    -D CMAKE_INSTALL_PREFIX=/usr \
    -D CMAKE_BUILD_TYPE=Release \
    -D BOOTSTRAP_CMAKE_TOOLCHAIN_FILE="cmake.config" \
    -D COMPILER_RT_BUILD_XRAY=OFF \
    -D COMPILER_RT_STANDALONE_BUILD=ON \
    -D CMAKE_C_FLAGS="-Wno-unused-command-line-argument \
-pthread \
-pipe \
-fno-pie \
-fPIC \
-fstack-protector-strong \
-DLIBCXX_HAS_MUSL_LIBC -D_LIBCPP_HAS_MUSL_LIBC \
--sysroot=$KISS_ROOT ${CMAKE_C_FLAGS-}" \
    -D CMAKE_CXX_FLAGS="$CXXFLAGS -Wno-unused-command-line-argument \
-lexecinfo \
-pthread \
-pipe \
-fno-pie \
-fPIC \
-fstack-protector-strong \
-DLIBCXX_HAS_MUSL_LIBC -D_LIBCPP_HAS_MUSL_LIBC \
-D_LIBCPP_STD_VER=23 \
-DLLVM_CXX_STD=20 \
-std=c++20 \
--sysroot=$KISS_ROOT ${CMAKE_CXX_FLAGS-}" \
    -D COMPILER_RT_BUILD_SANITIZERS=OFF \
    -D LLVM_REQUIRED_CXX_STANDARD=20 \
    -D LLVM_CXX_STD:STRING=20 \
    -D _LIBCPP_STD_VER=23 \
    -D _LIBCPP_HAS_MUSL_LIBC=ON \
    -D LIBCXX_HAS_MUSL_LIBC=ON \
    -D COMPILER_RT_DEFAULT_TARGET_TRIPLE="$KISS_XHOST_TRIPLE" \
-D COMPILER_RT_BUILD_BUILTINS=ON \
-D COMPILER_RT_BUILD_STANDALONE_LIBATOMIC=ON \
    -D _LIBCPP_PROVIDES_DEFAULT_RUNE_TABLE=ON

    # -DLLVM_ENABLE_LIBCXX -DLLVM_ENABLE_LIBCXXABI \
    # -lexecinfo
    # -isystem /usr/include/tirpc
    # -D_LIBCPP_STD_VER=23 \
    # -std=c++20 \
    # -DCMAKE_CXX_FLAGS="-lexecinfo -isystem /usr/include/tirpc $CMAKE_CXX_FLAGS" \
cmake --build   objects
cmake --install objects

# $1 = $HOME/.cache/kiss/proc/pkg/compiler-rt
# $2 = 14.0.3

cd "$1"
mkdir -p usr/lib/clang/$2/lib
rsync -a usr/lib/linux usr/lib/clang/$2/lib
